[platformio]
; Set project-wide locations (base is the CPS project folder)
src_dir = OOP/CPS-CyberPhysicalSystems
lib_dir = OOP/CPS-CyberPhysicalSystems/lib

[env:uno]
platform = atmelavr
board = uno
framework = arduino
; Only build core sources
build_src_filter = +<src/> -<examples/>
; Optional: enable extra warnings
build_flags = -Wall -Wextra -I OOP/CPS-CyberPhysicalSystems/lib
; Monitor settings
monitor_speed = 9600

[env:uno_demo]
platform = atmelavr
board = uno
framework = arduino
; Only build demo sketch sources
build_src_filter = +<examples/Pr1_Demo/src/> -<src/>
build_flags = -Wall -Wextra -I OOP/CPS-CyberPhysicalSystems/lib
monitor_speed = 115200
